version: '2'

#networks:
#    app-tier:
#      driver: bridge

services:

  minio:
    image: 'bitnami/minio:latest'
    ports:
        - '9000:9000'
        - '9001:9001'
    environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=password
    #networks:
    #    - app-tier
